### ISSUE TITLE
Erro no Sandbox - Geração de Card Token

### ISSUE THREAD

**Issue by rpraes** [DeveloperCielo/API-3.0-Java#11]
Este serviço se encontra disponível no ambiente Sandbox?

 Estou testando gerar um token de teste e estou recebendo a seguinte exception:

java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:196)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:442)
	at sun.security.ssl.InputRecord.read(InputRecord.java:480)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:927)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1312)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1339)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1323)

**Comment by netojoaobatista** [comment]
@rpraes, aparentemente o problema não é na geração de token, mas no protocolo; consegue confirmar se está utilizando TLS 1.2?

**Comment by rpraes** [comment]
@netojoaobatista, me parece que é problema no protocolo mesmo, pois testei com a 1.8 e funcionou, na 1.7 que acontece esse problema.

**Comment by netojoaobatista** [comment]
Então é isso. No JDK 8 o TLS 1.2 já é default enquanto no JDK 7, apesar de suportado, não é default. Veja: https://blogs.oracle.com/java-platform-group/entry/java_8_will_use_tls
