### ISSUE TITLE
{"Message":"Merchant not found"}

### ISSUE THREAD

**Issue by alexjosesilva** [DeveloperCielo/API-3.0-Java#43]
Ao executar o trecho do código:
String MerchantKey = "fwb6pecDw2Oh2A9d98rcAqdNQ8Rn4KB273pNLbPQ";
		
		// Configure seu merchant
		Merchant merchant = new Merchant(MerchantID, MerchantKey);
		

		// Informe os dados do cartão que irá tokenizar
		CardToken cardToken = new CardToken().setBrand("Visa")
		                                     .setCardNumber("4532117080573700")
		                                     .setHolder("Comprador T Cielo")
		                                     .setExpirationDate("12/2018");

		// Crie o Token para o cartão
		try {
			// // Configure o SDK com seu merchant e o ambiente apropriado para
			// gerar o token
			cardToken = new CieloEcommerce(merchant, Environment.SANDBOX).createCardToken(cardToken);
			
			String generatedToken = cardToken.getCardToken();

			System.out.printf("CardToken: %s\n", generatedToken);
		} catch (CieloRequestException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}

### **Recebo essa mensagem:**

**{"Message":"Merchant not found"}
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
	at com.google.gson.Gson.fromJson(Gson.java:891)
	at com.google.gson.Gson.fromJson(Gson.java:844)
	at com.google.gson.Gson.fromJson(Gson.java:793)
	at com.google.gson.Gson.fromJson(Gson.java:765)
	at cieloecommerce.sdk.ecommerce.request.AbstractSaleRequest.parseResponse(AbstractSaleRequest.java:124)
	at cieloecommerce.sdk.ecommerce.request.AbstractSaleRequest.readResponse(AbstractSaleRequest.java:96)
	at cieloecommerce.sdk.ecommerce.request.CreateCartTokenRequest.execute(CreateCartTokenRequest.java:29)
	at cieloecommerce.sdk.ecommerce.CieloEcommerce.createCardToken(CieloEcommerce.java:88)
	at cieloecommerce.sdk.ecommerce.Teste1.main(Teste1.java:35)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
	at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:350)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:70)
	at com.google.gson.Gson.fromJson(Gson.java:879)**

**Comment by frekele** [comment]
@alexjosesilva 

conforme o trecho do stacktrace que você postou, parece  que o parametro Merchant não está sendo informado.

Pelo que vejo no teu exemplo, se o MerchantID e MerchantKey não estiverem null ou empty, você parece estar fazendo certo.

Parece que possivelmente é um problema com o gson ao fazer o parse do objeto montado  e enviar para comunicação com a API.

Você pode fazer uma PR, mas provavelmente vai demorar para alguém da cielo com boa vontade liberar o merge dela ao master.
