### ISSUE TITLE
Obtendo SocketException na requisição

### ISSUE THREAD

**Issue by leandrobh3** [DeveloperCielo/API-3.0-Java#6]
Estou obtendo SocketException nos primeiros testes que estou realizando, não sei por qual motivo...

java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:196)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	...

Isto ocorre em CreateSaleRequest.java no momento de fazer a requisição, na instrução:

HttpResponse response = sendRequest(request);

Agradeço qualquer resposta! 

Obrigado.

**Comment by netojoaobatista** [comment]
A integração precisa, necessariamente, ocorrer em `TLS 1.2`. Verifique a versão do Java que você está utilizando e verifique o suporte. O Java 8 já trabalha com `TLS 1.2` por padrão.
